### ISSUE TITLE
Update build script to publish to staging.nuget.org 

### ISSUE THREAD

**Issue by vijayrkn** [sayedihashimi/publish-module#41]
We should have a branch which can be used to publish to staging.nuget.org.

We should also think about how we can make it easier to use a specific nuget source instead of always relying on the default users nuget.config file.

**Comment by sayedihashimi** [comment]
You can now publish to staging with the ```publish-staging``` branch.

I also added a ```nugetUrl``` parameter to default publish and wired it up in ```package-downloader``` so we should be good here. Closing.
