### ISSUE TITLE
File system publish fails if there is a space in the output path

### ISSUE THREAD

**Issue by vijayrkn** [sayedihashimi/publish-module#43]
If there is a space in the output path , then the powershell script fails:

Publishing files to c:\Temp Folder
Calling msdeploy to publish to file system with the command: [C:\Program Files (x86)\IIS\Microsoft Web Deploy V3\msdeploy.exe -source:contentPath='C:\Users\vramak\AppData\Local\Temp\AspNetPublish\WebApplication261-93\' -dest:contentPath='c:\Temp Folder' -verb:sync -usechecksum -enableRule:DoNotDeleteRule -retryAttempts:2 -disablerule:BackupRule]
Microsoft.Web.Deployment.DeploymentException: Unrecognized argument '"-dest:contentPath='c:\Temp Folder'"'. All arguments must begin with "-".
   at MSDeploy.MSDeploy.HandleArgument(String input, Boolean help)
   at MSDeploy.MSDeploy..ctor(Boolean debug,
 Boolean trace, Boolean help, IEnumerable`1 args)
   at MSDeploy.MSDeploy.Main(String[] unusedArgs)

INVOKEPOWERSHELL(0,0): Error count: 1.

**Comment by sayedihashimi** [comment]
I have emailed the powershell team with a sample asking for some help

**Comment by sayedihashimi** [comment]
@vijayrkn this is done right? If so can you close it?
