### ISSUE TITLE
ERROR_COULD_NOT_FIND_APPROOT_FOLDER

### ISSUE THREAD

**Issue by Bartmax** [sayedihashimi/publish-module#50]
Just trying to publish a mvc 6 default template (web api) project to azure (importing publishing profile from the publishing wizard, info is correct but on preview or publish I receive :

 ```
1>------ Build started: Project: MayaKin.Web, Configuration: Release Any CPU ------
Inside GatherAllFilesToPublish
Environment variables:
Path=C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\\Extensions\Microsoft\Web Tools\External;%PATH%;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\\Extensions\Microsoft\Web Tools\External\git
C:\Users\Bart\.k\runtimes\kre-clr-win-x86.1.0.0-beta3-11030\bin\kpm.cmd bundle "C:\Bartmax\MayaKin\MayaKin\src\MayaKin.Web" --out "C:\Users\Bart\AppData\Local\Temp\AspNetPublish\MayaKin.Web-42" --configuration Release --runtime kre-coreclr-win-x64.1.0.0-beta3 --wwwroot-out "wwwroot" --quiet
1>
1>  Build succeeded.
1>      0 Warning(s).
1>      0 Error(s).
1>
1>  Time elapsed 00:00:00.0860073
1>
========== Build: 1 succeeded or up-to-date, 0 failed, 0 skipped ==========
Time elapsed 00:00:00.4172004
C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\Web\Microsoft.AspNet.Publishing.targets(205,5): Error ERROR_COULD_NOT_FIND_APPROOT_FOLDER: Web deployment task failed. (Could not map the path 'MayaKin__Staging' to an approot folder.  Make sure the relative path you specify points to the root of an application.
  Obtenga más información en: http://go.microsoft.com/fwlink/?LinkId=221672#ERROR_COULD_NOT_FIND_APPROOT_FOLDER.)
Publish failed to deploy.
```

**Comment by Bartmax** [comment]
found out the problem with the name on azure being <name>__staging for the deployment slot. Deploying to the main slot works.

**Comment by sayedihashimi** [comment]
@vijayrkn do you know if this is a known issue? I'm not aware of it.

**Comment by Bartmax** [comment]
@vijayrkn no, pretty sure this is unknown.

**Comment by sayedihashimi** [comment]
@bartmax what happens if you Uncheck Use Powershell script on the settings tab?

**Comment by Bartmax** [comment]
same:

´´´
C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\Web\Microsoft.AspNet.Publishing.targets(205,5): Error ERROR_COULD_NOT_FIND_APPROOT_FOLDER: Web deployment task failed. (Could not map the path 'MayaKin__Staging' to an approot folder.  Make sure the relative path you specify points to the root of an application.
  Obtenga más información en: http://go.microsoft.com/fwlink/?LinkId=221672#ERROR_COULD_NOT_FIND_APPROOT_FOLDER.)
Publish failed to deploy.
´´´

**Comment by sayedihashimi** [comment]
I've opened a new issue for this at https://github.com/aspnet/Tooling/issues/15. That is where the team is tracking issues, will close this item.
