### ISSUE TITLE
[Package]: Change DesktopBuildPackageLocation to PackageLocation

### ISSUE THREAD

**Issue by sayedihashimi** [sayedihashimi/publish-module#55]
The property for package for the dest path is ```DesktopBuildPackageLocation``` we should change this to ```PackageLocation```

**Comment by artcolman** [comment]
I am trying to determine if there is another version of this property that is used when building using a TFS Build Server and hence the package is not on the "desktop" it sounds like I am safe in assuming that there is not another property as a change is being suggested.

**Comment by sayedihashimi** [comment]
The name is a hold over from previous publish support, there should be just one property.

**Comment by sayedihashimi** [comment]
Moved to https://github.com/aspnet/vsweb-publish/issues/5
